name: Core Tests

on:
  push: # Branches main & cicd
    branches: [main, cicd]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu    
        uv pip install -r requirements.txt
        uv pip install -e .

    - name: Run tests
      run: |
        pytest tests/