name: Core Tests

on:
  push: # Branches main & cicd
    branches: [main, cicd]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install requirements
      run: |
        pip install uv
        uv pip install --system --upgrade torch torchvision --index-url https://download.pytorch.org/whl/cpu
        uv pip install --system --upgrade -r requirements.txt
        uv pip install --system --upgrade -e .

    - name: Run tests
      run: |
        pytest tests/