# TODO

# Deploy Flask Web API to GCR
name: Deploy

on:
  push: # Branches main & cicd
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2